# Generated by Django 3.1.1 on 2021-06-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('desc', models.TextField(blank=True, default='Text here', null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, default='media/no-image.jpg', upload_to='media')),
                ('author', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Your Name', max_length=50)),
                ('email', models.EmailField(default='example@gmail.com', max_length=100)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Completation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.basemodel')),
                ('url', models.URLField(blank=True, null=True)),
            ],
            bases=('blog.basemodel',),
        ),
        migrations.CreateModel(
            name='ThesisProject',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.basemodel')),
                ('document', models.FileField(blank=True, upload_to='media/pdf/')),
                ('google_drive_url', models.URLField(blank=True, null=True)),
            ],
            bases=('blog.basemodel',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.basemodel')),
                ('images', models.ManyToManyField(blank=True, to='blog.Images')),
            ],
            bases=('blog.basemodel',),
        ),
    ]
