# Generated by Django 3.1.1 on 2021-06-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='author',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
